modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="zt" #mandatory
version="1.15.2-0.1" #mandatory
displayName="Zinth Tools" #mandatory
credits="Vectorwing for heavily inspiring me to make my own mod"
description='''
This is a mod that adds new tools!
'''
[[dependencies.zt]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.zt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
